version: "3.3"
name: "coyotomic"
# Servidor nginx
services:
  # Configuración de php-fpm
  php-fpm:
    build:
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: "coyotomic"
    volumes:
      - ./:/var/www/html/
